import { Product } from "./types/Product";

export const sampleProducts:Product [] = [
    {
        name: 'dress 1',
        slug: 'dress-1',
        category: 'dress',
        image: '../images/dress1.png',
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality dress',
    },
    {
        name: 'dress 2',
        slug: 'dress-2',
        category: 'dress',
        image: '../images/dress2.jpg',
        price: 120,
        countInStock: 10,
        brand: 'Puma',
        rating: 4.5,
        numReviews: 10,
        description: 'better quality dress',
    },
    {
        name: 'dress 3',
        slug: 'dress-3',
        category: 'dress',
        image: '../images/dress3.jpg',
        price: 120,
        countInStock: 10,
        brand: 'Loung',
        rating: 4.5,
        numReviews: 10,
        description: 'Good quality dress',
    },
    {
        name: 'dress 4',
        slug: 'dress-4',
        category: 'dress',
        image: '../images/dress2.jpg',
        price: 120,
        countInStock: 10,
        brand: 'Goat',
        rating: 4.5,
        numReviews: 10,
        description: 'super quality dress',
    },
]